### ISSUE TITLE
The URL for each individual article

### ISSUE THREAD

**Issue by myKingEdem** [inded/Jekyll_modern-blog#1]
I'm trying to see if I can use this theme for a project I'm currently working on. I need to have the URLs for each individual page/article to send data to another site (app) based on user behavior.

Can you point me in the right direction?

**Comment by Wferr** [comment]
Your wanting it to be able to link to posts correct?

**Comment by myKingEdem** [comment]
Yes, so people can share the individual link for each post.

**Comment by oconnor663** [comment]
Related: I can't hit Back to return to the blog home page from an individual article.

**Comment by Wferr** [comment]
@oconnor663 these issues are both related to the fact that the website never reloads or switches pages. Im working on a solution but it might take a while.

**Comment by oconnor663** [comment]
Is https://github.com/browserstate/history.js the way most people handle this sort of thing?

**Comment by Wferr** [comment]
@oconnor663 most likely, ill work on implementing that shortly. Gotta catch up with school first.

**Comment by Wferr** [comment]
@oconnor663 see Pull Request #3

**Comment by oconnor663** [comment]
Thanks!
